name: lint-test
on: [push]

jobs:
  lint-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          verbose: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
  build-push-ar:
    needs: [lint-test]
    uses: libops/actions/.github/workflows/build-push.yml@main
    with:
      image: shared/retro
    permissions:
      contents: read
      id-token: write
    secrets: inherit
